// scripts/vue/cart/components/Item.vue
<template>
  <div class="c-item">
    <div class="u-noLineHeight">
      <img :src="item.featured_image.url" />
    </div>
    <div class="c-item__details">
      <p>{{ item.title }}</p>
      <div class="c-item__bottom">
        <div class="c-item__actions">
          <quantity
            :miniumum="0"
            :quantity="item.quantity"
            @increment="$emit('increment')"
            @decrement="$emit('decrement')"
          />
        </div>
        <button @click="$emit('remove')">
          <v-icon name="hi-trash" />
        </button>
      </div>
    </div>
  </div>
</template>

<script>
  import Quantity from '../../quantity/Quantity.vue';

  export default {
    props: {
      item: {
        type: Object
      }
    },
    components: {
      Quantity
    },
  }
</script>

// scripts/preact/apps/cart/components/Item.jsx
import { h } from 'preact';
import Quantity from '../../../components/quantity/Quantity.jsx';

const { formatMoney } = window;

export default function Item({ item, handleInc, handleDec, handleRemove }) {
  return (
    <div className="c-item">
      <div className="u-noLineHeight">
        <a href={item.url}>
          <img src={item.featured_image.url} />
        </a>
      </div>
      <div className="c-item__details">
        <p>{item.title}</p>
        <p>{formatMoney(item.price)}</p>
        <div className="c-item__bottom">
          <div className="c-item__actions">
            <Quantity
              miniumum={0}
              quantity={item.quantity}
              handleIncrement={handleInc}
              handleDecrement={handleDec}
            />
          </div>
          <button onClick={handleRemove}>X</button>
        </div>
      </div>
    </div>
  );
}
